### ISSUE TITLE
Chapter Organisers Wanted

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/feedback#4]
- AngularJS
- ReactJS
- EmberJS
- NodeJS
- MeteorJS
- ...JS

you're a total fan of xyJS? Become a BarcelonaJS Chapter Organiser! Tell us if you're interested.

**Comment by ifraixedes** [comment]
@PatrickHeneise I agree with you, JS is a very big thing.

To have better management and provide better experience to the community, we should find people who want to take ownership on the specific topics.

I don't think that a requirement is to have one event a month, it may be something to achieve, but some topics may not have that amount of interest and speakers to run events with that frequency; so don't get scary to take the ownership of the topic which is one of your main interests.

Everybody in the organisation, are very busy, so it's hard to move things, so I feel that giving the ownership of each topic to a a few organisers (ideally not just one, is too much work for one person), who can operate independently and all of us only commit for the general purpose of getting an awesome JS Barcelona community, we can become more agile and push more to the mentioned general purpose.

Please, if you have a small interest in becoming a Chapter Organiser, but you aren't sure because you would like to ask or figure out things before taking it, drop a comment or reach us on [slack group](http://barcelonajs.herokuapp.com) if you want to keep some privacy.

We are looking forward to hearing from you

**Comment by steffen** [comment]
You missed the best: Ext JS! 😀

It's kind of a niche/enterprise framework, so not sure what the interest for it is out there. I would certainly be interested in organizing a Sencha / Ext JS meetup (once a year? 😀).

**Comment by ifraixedes** [comment]
In my opinion, it's better that it exist.
Even though the amount of people interested may be low, I think that it can be the path for those who are interested in talking, listening, learning, etc., about it

**Comment by steffen** [comment]
Yeah, we can give it a try. What would be the steps to set one up? Will there be a getting started guide for chapter organizers or something like that? :)

**Comment by ifraixedes** [comment]
We're newbie on it, however with your interest, we're going to discuss in the following days so we can provide you a response with more specific information as soon as possible.

Thank you very much for your interest
Stay tuned!

**Comment by steffen** [comment]
👍Thanks!
